"""Racecourse registry and crawl-scope filtering (expandable allowlist)."""

from src.racecourses.registry import (
    DEFAULT_ALLOWED_CODES,
    GOLESTAN_CODES,
    RACECOURSES,
    Racecourse,
    ensure_racecourse,
    get_racecourse,
    is_code_allowed,
    is_racecourse_allowed,
    normalize_track_key,
    parse_allowed_codes,
    resolve_racecourse,
    synthesize_racecourse,
)
from src.racecourses.scope import (
    OutOfScopeRacecourseError,
    allowed_codes_from_settings,
    ensure_track_in_scope,
)
from src.racecourses.track_config import (
    TRACK_CONFIGURATIONS,
    TrackConfiguration,
    TrackContext,
    build_track_context,
    categorize_straight_length,
    comparable_on_straight,
    configuration_table_rows,
    get_track_configuration,
    propose_straight_length_update,
    resolve_track_configuration,
    straight_length_features,
)

__all__ = [
    "DEFAULT_ALLOWED_CODES",
    "GOLESTAN_CODES",
    "OutOfScopeRacecourseError",
    "RACECOURSES",
    "TRACK_CONFIGURATIONS",
    "Racecourse",
    "TrackConfiguration",
    "TrackContext",
    "allowed_codes_from_settings",
    "build_track_context",
    "categorize_straight_length",
    "comparable_on_straight",
    "configuration_table_rows",
    "ensure_racecourse",
    "ensure_track_in_scope",
    "get_racecourse",
    "get_track_configuration",
    "is_code_allowed",
    "is_racecourse_allowed",
    "normalize_track_key",
    "parse_allowed_codes",
    "propose_straight_length_update",
    "resolve_racecourse",
    "resolve_track_configuration",
    "straight_length_features",
    "synthesize_racecourse",
]
